[package]
name = "ynab-sync"
version = "0.1.0"
authors = ["Rok Garbas <rok@garbas.si>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/garbas/ynab-sync"
repository = "https://github.com/garbas/ynab-sync"
readme = "README.md"
description = "Sync transactions to your YNAB account"

[dependencies]
chrono = { version = "*", features = ["serde"] }
clap = "*"
failure = "*"
oauth2 = "*"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_str = "*"
